#if !defined(INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UXLAPY_H)
#define INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UXLAPY_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [2:isize+0]
// number of additional cells w.r.t. 1, isize
#define UXLAPY_LNADD_0 -1
#define UXLAPY_UNADD_0 0
// number of cells
#define UXLAPY_NITEMS_0(I) (I-1)
#define UXLAPY(I) (uxlapy[(I-2)])

#endif // INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UXLAPY_H
