#if !defined(INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UZLAPX_H)
#define INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UZLAPX_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define UZLAPX_LNADD_0 0
#define UZLAPX_UNADD_0 0
// number of cells
#define UZLAPX_NITEMS_0(I) (I+0)
#define UZLAPX(I) (uzlapx[(I-1)])

#endif // INITIAL_CONDITIONS_INCLUDE_ARRAYS_DOMAIN_UZLAPX_H
