#if !defined(INCLUDE_ARRAYS_FLUID_P_H)
#define INCLUDE_ARRAYS_FLUID_P_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 0:jsize+1, 0:ksize+1]
// number of additional cells w.r.t. 1, [i-k]size
#define P_LNADD_0 1
#define P_UNADD_0 1
#define P_LNADD_1 1
#define P_UNADD_1 1
#define P_LNADD_2 1
#define P_UNADD_2 1
// number of cells
#define P_NITEMS_0(I) (I+2)
#define P_NITEMS_1(J) (J+2)
#define P_NITEMS_2(K) (K+2)
#define P_NITEMS_ALL P_NITEMS_0(isize) * P_NITEMS_1(jsize) * P_NITEMS_2(ksize)
#define P(I, J, K) (p[(I  ) + P_NITEMS_0(isize) * ((J  ) + (K  ) * P_NITEMS_1(jsize))])

#endif // INCLUDE_ARRAYS_FLUID_P_H
