#if !defined(INCLUDE_ARRAYS_FLUID_UY_H)
#define INCLUDE_ARRAYS_FLUID_UY_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 0:jsize+1, 0:ksize+1]
// number of additional cells w.r.t. 1, [i-k]size
#define UY_LNADD_0 1
#define UY_UNADD_0 1
#define UY_LNADD_1 1
#define UY_UNADD_1 1
#define UY_LNADD_2 1
#define UY_UNADD_2 1
// number of cells
#define UY_NITEMS_0(I) (I+2)
#define UY_NITEMS_1(J) (J+2)
#define UY_NITEMS_2(K) (K+2)
#define UY_NITEMS_ALL UY_NITEMS_0(isize) * UY_NITEMS_1(jsize) * UY_NITEMS_2(ksize)
#define UY(I, J, K) (uy[(I  ) + UY_NITEMS_0(isize) * ((J  ) + (K  ) * UY_NITEMS_1(jsize))])

#endif // INCLUDE_ARRAYS_FLUID_UY_H
