#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LXX_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LXX_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1]
#define LXX(I, J) (lxx[(I-1) + (isize+0) * (J  )])
#define LXX_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_LXX_H
