#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LXZ_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LXZ_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 3
// [1 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define LXZ(I, J, K) (lxz[(I-1) + (isize+1) * ((J  ) + (jsize+2) * (K  ))])
#define LXZ_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, {1, 1}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_FLUID_LXZ_H
