#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LYX0_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LYX0_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1], [0 : jsize+1], [0 : ksize+1]
#define LYX0(I, J, K) (lyx0[(I-1) + (isize+1) * ((J  ) + (jsize+2) * (K  ))])
#define LYX0_NADDS (int [NDIMS][2]){ {0, 1}, {1, 1}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_LYX0_H
