#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LYY0_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LYY0_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1]
#define LYY0(I, J) (lyy0[(I-1) + (isize+0) * (J  )])
#define LYY0_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_LYY0_H
