#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LYY1_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LYY1_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1], [0 : ksize+1]
#define LYY1(I, J, K) (lyy1[(I-1) + (isize+0) * ((J  ) + (jsize+2) * (K  ))])
#define LYY1_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_LYY1_H
