#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LYY1_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LYY1_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1]
#define LYY1(I, J) (lyy1[(I-1) + (isize+0) * (J  )])
#define LYY1_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_LYY1_H
