#if !defined(INCLUDE_ARRAY_MACROS_FLUID_LZY_H)
#define INCLUDE_ARRAY_MACROS_FLUID_LZY_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 3
// [1 : isize+0], [0 : jsize+1], [0 : ksize+1]
#define LZY(I, J, K) (lzy[(I-1) + (isize+0) * ((J  ) + (jsize+2) * (K  ))])
#define LZY_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, {1, 1}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_FLUID_LZY_H
