#if !defined(INCLUDE_ARRAYS_DOMAIN_DXF_H)
#define INCLUDE_ARRAYS_DOMAIN_DXF_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define DXF_LNADD_0 0
#define DXF_UNADD_0 0
// number of cells
#define DXF_NITEMS_0(I) (I+0)
#define DXF(I) (dxf[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_DXF_H
