#if !defined(INCLUDE_ARRAYS_DOMAIN_PLAPX_H)
#define INCLUDE_ARRAYS_DOMAIN_PLAPX_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define PLAPX_LNADD_0 0
#define PLAPX_UNADD_0 0
// number of cells
#define PLAPX_NITEMS_0(I) (I+0)
#define PLAPX(I) (plapx[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_PLAPX_H
