#if !defined(INCLUDE_ARRAYS_DOMAIN_PLAPY_H)
#define INCLUDE_ARRAYS_DOMAIN_PLAPY_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define PLAPY_LNADD_0 0
#define PLAPY_UNADD_0 0
// number of cells
#define PLAPY_NITEMS_0(I) (I+0)
#define PLAPY(I) (plapy[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_PLAPY_H
