#if !defined(INCLUDE_ARRAYS_DOMAIN_UXLAPX_H)
#define INCLUDE_ARRAYS_DOMAIN_UXLAPX_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [2:isize+0]
// number of additional cells w.r.t. 1, isize
#define UXLAPX_LNADD_0 -1
#define UXLAPX_UNADD_0 0
// number of cells
#define UXLAPX_NITEMS_0(I) (I-1)
#define UXLAPX(I) (uxlapx[(I-2)])

#endif // INCLUDE_ARRAYS_DOMAIN_UXLAPX_H
