#if !defined(INCLUDE_ARRAYS_DOMAIN_UYLAPX_H)
#define INCLUDE_ARRAYS_DOMAIN_UYLAPX_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define UYLAPX_LNADD_0 0
#define UYLAPX_UNADD_0 0
// number of cells
#define UYLAPX_NITEMS_0(I) (I+0)
#define UYLAPX(I) (uylapx[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_UYLAPX_H
