#if !defined(INCLUDE_ARRAYS_DOMAIN_UYLAPY_H)
#define INCLUDE_ARRAYS_DOMAIN_UYLAPY_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0]
// number of additional cells w.r.t. 1, isize
#define UYLAPY_LNADD_0 0
#define UYLAPY_UNADD_0 0
// number of cells
#define UYLAPY_NITEMS_0(I) (I+0)
#define UYLAPY(I) (uylapy[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_UYLAPY_H
