#if !defined(INCLUDE_ARRAYS_DOMAIN_XC_H)
#define INCLUDE_ARRAYS_DOMAIN_XC_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1]
// number of additional cells w.r.t. 1, isize
#define XC_LNADD_0 1
#define XC_UNADD_0 1
// number of cells
#define XC_NITEMS_0(I) (I+2)
#define XC(I) (xc[(I  )])

#endif // INCLUDE_ARRAYS_DOMAIN_XC_H
