#if !defined(INCLUDE_ARRAYS_DOMAIN_XF_H)
#define INCLUDE_ARRAYS_DOMAIN_XF_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+1]
// number of additional cells w.r.t. 1, isize
#define XF_LNADD_0 0
#define XF_UNADD_0 1
// number of cells
#define XF_NITEMS_0(I) (I+1)
#define XF(I) (xf[(I-1)])

#endif // INCLUDE_ARRAYS_DOMAIN_XF_H
