#if !defined(INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_P_H)
#define INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_P_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define P_LNADD_0 1
#define P_UNADD_0 1
#define P_LNADD_1 0
#define P_UNADD_1 0
#define P_LNADD_2 0
#define P_UNADD_2 0
// number of cells
#define P_NITEMS_0(I) (I+2)
#define P_NITEMS_1(J) (J+0)
#define P_NITEMS_2(K) (K+0)
#define P_NITEMS_ALL P_NITEMS_0(isize) * P_NITEMS_1(jsize) * P_NITEMS_2(ksize)
#define P(I, J, K) (p[(I  ) + P_NITEMS_0(isize) * ((J-1) + (K-1) * P_NITEMS_1(jsize))])

#endif // INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_P_H
