#if !defined(SRC_STATISTICS_ARRAYS_UX1_H)
#define SRC_STATISTICS_ARRAYS_UX1_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+1, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define UX1_LNADD_0 0
#define UX1_UNADD_0 1
#define UX1_LNADD_1 0
#define UX1_UNADD_1 0
#define UX1_LNADD_2 0
#define UX1_UNADD_2 0
// number of cells
#define UX1_NITEMS_0(I) (I+1)
#define UX1_NITEMS_1(J) (J+0)
#define UX1_NITEMS_2(K) (K+0)
#define UX1_NITEMS_ALL UX1_NITEMS_0(isize) * UX1_NITEMS_1(jsize) * UX1_NITEMS_2(ksize)
#define UX1(I, J, K) (ux1[(I-1) + UX1_NITEMS_0(isize) * ((J-1) + (K-1) * UX1_NITEMS_1(jsize))])

#endif // SRC_STATISTICS_ARRAYS_UX1_H
