#if !defined(SRC_STATISTICS_ARRAYS_UY1_H)
#define SRC_STATISTICS_ARRAYS_UY1_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define UY1_LNADD_0 1
#define UY1_UNADD_0 1
#define UY1_LNADD_1 0
#define UY1_UNADD_1 0
#define UY1_LNADD_2 0
#define UY1_UNADD_2 0
// number of cells
#define UY1_NITEMS_0(I) (I+2)
#define UY1_NITEMS_1(J) (J+0)
#define UY1_NITEMS_2(K) (K+0)
#define UY1_NITEMS_ALL UY1_NITEMS_0(isize) * UY1_NITEMS_1(jsize) * UY1_NITEMS_2(ksize)
#define UY1(I, J, K) (uy1[(I  ) + UY1_NITEMS_0(isize) * ((J-1) + (K-1) * UY1_NITEMS_1(jsize))])

#endif // SRC_STATISTICS_ARRAYS_UY1_H
