#if !defined(INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UX_H)
#define INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UX_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+1, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define UX_LNADD_0 0
#define UX_UNADD_0 1
#define UX_LNADD_1 0
#define UX_UNADD_1 0
#define UX_LNADD_2 0
#define UX_UNADD_2 0
// number of cells
#define UX_NITEMS_0(I) (I+1)
#define UX_NITEMS_1(J) (J+0)
#define UX_NITEMS_2(K) (K+0)
#define UX_NITEMS_ALL UX_NITEMS_0(isize) * UX_NITEMS_1(jsize) * UX_NITEMS_2(ksize)
#define UX(I, J, K) (ux[(I-1) + UX_NITEMS_0(isize) * ((J-1) + (K-1) * UX_NITEMS_1(jsize))])

#endif // INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UX_H
