#if !defined(INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UZ_H)
#define INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UZ_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define UZ_LNADD_0 1
#define UZ_UNADD_0 1
#define UZ_LNADD_1 0
#define UZ_UNADD_1 0
#define UZ_LNADD_2 0
#define UZ_UNADD_2 0
// number of cells
#define UZ_NITEMS_0(I) (I+2)
#define UZ_NITEMS_1(J) (J+0)
#define UZ_NITEMS_2(K) (K+0)
#define UZ_NITEMS_ALL UZ_NITEMS_0(isize) * UZ_NITEMS_1(jsize) * UZ_NITEMS_2(ksize)
#define UZ(I, J, K) (uz[(I  ) + UZ_NITEMS_0(isize) * ((J-1) + (K-1) * UZ_NITEMS_1(jsize))])

#endif // INITIAL_CONDITIONS_INCLUDE_ARRAYS_FLUID_UZ_H
