#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H

// This file is generated by tools/define_arrays.py

// [0 : isize+1]
#define HXXC(I) (hxxc[(I  )])
#define HXXC_NADDS (int [2]){1, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H
