#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_HYXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_HYXC_H

// This file is generated by tools/define_arrays.py

// [0 : isize+1]
#define HYXC(I) (hyxc[(I  )])
#define HYXC_NADDS (int [2]){1, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_HYXC_H
