#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H

// This file is generated by tools/define_arrays.py

// [0 : isize+1]
#define JDXC(I) (jdxc[(I  )])
#define JDXC_NADDS (int [2]){1, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H
