# define macros to access arrays easily
# for 1D, x-face, x-center, and their distances are defined
# for ND, arrays to hold velocity, pressure, temperature, etc. are defined

import os
import sys
import re

def get_lnadd(lbound):
    # -1 -> -1
    #  0 ->  0
    # +1 -> +1
    return lbound

def get_unadd(ubound):
    # -1 -> -1
    #  0 ->  0
    # +1 -> +1
    return ubound

def get_lbound(lbound):
    # -1 -> "2"
    #  0 -> "1"
    # +1 -> "0"
    lbound = - lbound + 1
    return f"{lbound}"

def get_ubound(ubound, prefix):
    # -1 -> "isize-1"
    #  0 -> "isize+0"
    # +1 -> "isize+1"
    return f"{prefix}{ubound:+d}"

def get_nitems(string, lbound, ubound):
    ## get size of a vector whose lower- / upper-bounds are given
    ## e.g.
    ##    nitems = isize+1 if lbound = 1 and ubound = isize+1
    ##    nitems = jsize+2 if lbound = 0 and ubound = jsize+1
    # extract numbers
    s_ = re.sub("[a-zA-Z]", "", lbound.strip())
    e_ = re.sub("[a-zA-Z]", "", ubound.strip())
    s_ = int(s_)
    if e_ == "":
        e_ = 0
    else:
        e_ = int(e_)
    nitems = "({}{:+d})".format(string, e_ - s_ + 1)
    return nitems

def get_index(index, lbound):
    ## get index of a vector whose lower-bound is given
    ## e.g.
    ##    return I-1 if lbound is  1 to map I =  1 to the head of vector
    ##    return I+1 if lbound is -1 to map I = -1 to the head of vector
    if lbound == "0":
        return f"{index}  "
    else:
        val = -int(lbound)
        return f"{index}{val:+d}"

def get_index_1d(uname, lbound_0):
    iindex = get_index("I", lbound_0)
    string = (
        f"({iindex})"
    )
    return string

def get_index_2d(uname, lbound_0, lbound_1):
    iindex = get_index("I", lbound_0)
    jindex = get_index("J", lbound_1)
    string = (
        f"({iindex})"
        f" + "
        f"{uname}_NITEMS_0(isize)"
        f" * "
        f"({jindex})"
    )
    return string

def get_index_3d(uname, lbound_0, lbound_1, lbound_2):
    iindex = get_index("I", lbound_0)
    jindex = get_index("J", lbound_1)
    kindex = get_index("K", lbound_2)
    string = (
        f"({iindex})"
        f" + "
        f"{uname}_NITEMS_0(isize)"
        f" * "
        f"("
        f"({jindex})"
        f" + "
        f"({kindex})"
        f" * "
        f"{uname}_NITEMS_1(jsize)"
        f")"
    )
    return string

def attach_header_and_footer(file_name, body):
    # concatenate all to obtain an include guard
    include_guard = file_name.replace("/", "_")
    include_guard = include_guard.replace(".", "_")
    include_guard = include_guard.upper()
    # name of this python script
    script_name = sys.argv[0]
    header = (
            f"#if !defined({include_guard})\n"
            f"#define {include_guard}\n"
            f"\n"
            f"/*\n"
            f" * This file is generated by\n"
            f" *   {script_name}\n"
            f" */\n"
            f"\n"
    )
    footer = (
            f"\n"
            f"#endif // {include_guard}\n"
    )
    return "".join([header, body, footer])

def gen_1d(dname, vname, lbound_0, ubound_0):
    # prepare macros for one-dimensional vector
    lnadd_0 = get_lnadd(lbound_0)
    unadd_0 = get_unadd(ubound_0)
    lbound_0 = get_lbound(lbound_0)
    ubound_0 = get_ubound(ubound_0, "isize")
    uname = vname.strip().upper()
    index_1d = get_index_1d(uname, lbound_0)
    char_0 = "I"
    nitems_0 = get_nitems(char_0, lbound_0, ubound_0)
    body = (
            f"// [{lbound_0}:{ubound_0}]\n"
            f"// number of additional cells w.r.t. 1, isize\n"
            f"#define {uname}_LNADD_0 {lnadd_0}\n"
            f"#define {uname}_UNADD_0 {unadd_0}\n"
            f"// number of cells\n"
            f"#define {uname}_NITEMS_0({char_0}) {nitems_0}\n"
            f"#define {uname}({char_0}) ({vname}[{index_1d}])\n"
    )
    file_name = f"{dname}/{vname}.h"
    with open(file_name, "w") as f:
        text = attach_header_and_footer(file_name, body)
        f.write(text)

def gen_3d(dname, vname, lbound_0, ubound_0, lbound_1, ubound_1, lbound_2, ubound_2):
    # prepare macros for N-dimensional array
    lnadd_0 = get_lnadd(lbound_0)
    unadd_0 = get_unadd(ubound_0)
    lnadd_1 = get_lnadd(lbound_1)
    unadd_1 = get_unadd(ubound_1)
    lnadd_2 = get_lnadd(lbound_2)
    unadd_2 = get_unadd(ubound_2)
    lbound_0 = get_lbound(lbound_0)
    ubound_0 = get_ubound(ubound_0, "isize")
    lbound_1 = get_lbound(lbound_1)
    ubound_1 = get_ubound(ubound_1, "jsize")
    lbound_2 = get_lbound(lbound_2)
    ubound_2 = get_ubound(ubound_2, "ksize")
    uname = vname.strip().upper()
    index_2d = get_index_2d(uname, lbound_0, lbound_1)
    index_3d = get_index_3d(uname, lbound_0, lbound_1, lbound_2)
    char_0 = "I"
    char_1 = "J"
    char_2 = "K"
    nitems_0 = get_nitems(char_0, lbound_0, ubound_0)
    nitems_1 = get_nitems(char_1, lbound_1, ubound_1)
    nitems_2 = get_nitems(char_2, lbound_2, ubound_2)
    body = list()
    body.append((
            f"// [{lbound_0}:{ubound_0}, {lbound_1}:{ubound_1}, {lbound_2}:{ubound_2}]\n"
            f"// number of additional cells w.r.t. 1, [i-k]size\n"
            f"#define {uname}_LNADD_0 {lnadd_0}\n"
            f"#define {uname}_UNADD_0 {unadd_0}\n"
            f"#define {uname}_LNADD_1 {lnadd_1}\n"
            f"#define {uname}_UNADD_1 {unadd_1}\n"
            f"#define {uname}_LNADD_2 {lnadd_2}\n"
            f"#define {uname}_UNADD_2 {unadd_2}\n"
            f"// number of cells\n"
            f"#define {uname}_NITEMS_0({char_0}) {nitems_0}\n"
            f"#define {uname}_NITEMS_1({char_1}) {nitems_1}\n"
            f"#define {uname}_NITEMS_2({char_2}) {nitems_2}\n"
            f"#define {uname}_NITEMS_ALL {uname}_NITEMS_0(isize) * {uname}_NITEMS_1(jsize) * {uname}_NITEMS_2(ksize)\n"
            f"#define {uname}({char_0}, {char_1}, {char_2}) ({vname}[{index_3d}])\n"
    ))
    body = "".join(body)
    file_name = f"{dname}/{vname}.h"
    with open(file_name, "w") as f:
        text = attach_header_and_footer(file_name, body)
        f.write(text)

def domain():
    roots = (
            "include/arrays/domain",
            "initial_conditions/include/arrays/domain",
    )
    for root in roots:
        os.system(f"rm -f {root}/*.h")
        gen_1d(root, "xf",      0, +1)
        gen_1d(root, "xc",     +1, +1)
        gen_1d(root, "dxf",     0,  0)
        gen_1d(root, "dxc",     0, +1)
        gen_1d(root, "uxlapx", -1,  0)
        gen_1d(root, "uylapx",  0,  0)
        gen_1d(root, "uzlapx",  0,  0)
        gen_1d(root, "plapx",   0,  0)
        gen_1d(root, "uxlapy", -1,  0)
        gen_1d(root, "uylapy",  0,  0)
        gen_1d(root, "uzlapy",  0,  0)
        gen_1d(root, "plapy",   0,  0)

def fluid():
    roots = (
            "include/arrays/fluid",
            "initial_conditions/include/arrays/fluid",
    )
    # one halo cells for the former
    # no  halo cells for the latter
    nadds = (+1, 0)
    for n, root in enumerate(roots):
        os.system(f"rm -f {root}/*.h")
        gen_3d(root, "ux",  0, +1, nadds[n], nadds[n], nadds[n], nadds[n])
        gen_3d(root, "uy", +1, +1, nadds[n], nadds[n], nadds[n], nadds[n])
        gen_3d(root, "uz", +1, +1, nadds[n], nadds[n], nadds[n], nadds[n])
        gen_3d(root, "p",  +1, +1, nadds[n], nadds[n], nadds[n], nadds[n])

def fluid_internal():
    root = "src/fluid/arrays"
    os.system(f"rm -f {root}/*.h")
    gen_3d(root, "psi",    +1, +1, +1, +1, +1, +1)
    gen_3d(root, "srcuxa", -1,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuxb", -1,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuxg", -1,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuya",  0,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuyb",  0,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuyg",  0,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuza",  0,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuzb",  0,  0,  0,  0,  0,  0)
    gen_3d(root, "srcuzg",  0,  0,  0,  0,  0,  0)

def statistics():
    root = "src/statistics/arrays"
    os.system(f"rm -f {root}/*.h")
    gen_3d(root, "ux1",  0, +1, 0, 0, 0, 0)
    gen_3d(root, "ux2",  0, +1, 0, 0, 0, 0)
    gen_3d(root, "uy1", +1, +1, 0, 0, 0, 0)
    gen_3d(root, "uy2", +1, +1, 0, 0, 0, 0)
    gen_3d(root, "uz1", +1, +1, 0, 0, 0, 0)
    gen_3d(root, "uz2", +1, +1, 0, 0, 0, 0)

if __name__ == "__main__":
    # coordinates in the wall-normal direction
    domain()
    # velocity, pressure
    fluid()
    # scalar potential, source terms of RK
    fluid_internal()
    # arrays to store temporally-averaged statistics
    statistics()

