#if !defined(SRC_FLUID_ARRAYS_PSI_H)
#define SRC_FLUID_ARRAYS_PSI_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [0:isize+1, 0:jsize+1, 0:ksize+1]
// number of additional cells w.r.t. 1, [i-k]size
#define PSI_LNADD_0 1
#define PSI_UNADD_0 1
#define PSI_LNADD_1 1
#define PSI_UNADD_1 1
#define PSI_LNADD_2 1
#define PSI_UNADD_2 1
// number of cells
#define PSI_NITEMS_0(I) (I+2)
#define PSI_NITEMS_1(J) (J+2)
#define PSI_NITEMS_2(K) (K+2)
#define PSI_NITEMS_ALL PSI_NITEMS_0(isize) * PSI_NITEMS_1(jsize) * PSI_NITEMS_2(ksize)
#define PSI(I, J, K) (psi[(I  ) + PSI_NITEMS_0(isize) * ((J  ) + (K  ) * PSI_NITEMS_1(jsize))])

#endif // SRC_FLUID_ARRAYS_PSI_H
