#if !defined(SRC_FLUID_ARRAYS_SRCUZG_H)
#define SRC_FLUID_ARRAYS_SRCUZG_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define SRCUZG_LNADD_0 0
#define SRCUZG_UNADD_0 0
#define SRCUZG_LNADD_1 0
#define SRCUZG_UNADD_1 0
#define SRCUZG_LNADD_2 0
#define SRCUZG_UNADD_2 0
// number of cells
#define SRCUZG_NITEMS_0(I) (I+0)
#define SRCUZG_NITEMS_1(J) (J+0)
#define SRCUZG_NITEMS_2(K) (K+0)
#define SRCUZG_NITEMS_ALL SRCUZG_NITEMS_0(isize) * SRCUZG_NITEMS_1(jsize) * SRCUZG_NITEMS_2(ksize)
#define SRCUZG(I, J, K) (srcuzg[(I-1) + SRCUZG_NITEMS_0(isize) * ((J-1) + (K-1) * SRCUZG_NITEMS_1(jsize))])

#endif // SRC_FLUID_ARRAYS_SRCUZG_H
