#if !defined(SRC_FLUID_ARRAYS_SRCUZA_H)
#define SRC_FLUID_ARRAYS_SRCUZA_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define SRCUZA_LNADD_0 0
#define SRCUZA_UNADD_0 0
#define SRCUZA_LNADD_1 0
#define SRCUZA_UNADD_1 0
#define SRCUZA_LNADD_2 0
#define SRCUZA_UNADD_2 0
// number of cells
#define SRCUZA_NITEMS_0(I) (I+0)
#define SRCUZA_NITEMS_1(J) (J+0)
#define SRCUZA_NITEMS_2(K) (K+0)
#define SRCUZA_NITEMS_ALL SRCUZA_NITEMS_0(isize) * SRCUZA_NITEMS_1(jsize) * SRCUZA_NITEMS_2(ksize)
#define SRCUZA(I, J, K) (srcuza[(I-1) + SRCUZA_NITEMS_0(isize) * ((J-1) + (K-1) * SRCUZA_NITEMS_1(jsize))])

#endif // SRC_FLUID_ARRAYS_SRCUZA_H
