#if !defined(SRC_FLUID_ARRAYS_SRCUXG_H)
#define SRC_FLUID_ARRAYS_SRCUXG_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [2:isize+0, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define SRCUXG_LNADD_0 -1
#define SRCUXG_UNADD_0 0
#define SRCUXG_LNADD_1 0
#define SRCUXG_UNADD_1 0
#define SRCUXG_LNADD_2 0
#define SRCUXG_UNADD_2 0
// number of cells
#define SRCUXG_NITEMS_0(I) (I-1)
#define SRCUXG_NITEMS_1(J) (J+0)
#define SRCUXG_NITEMS_2(K) (K+0)
#define SRCUXG_NITEMS_ALL SRCUXG_NITEMS_0(isize) * SRCUXG_NITEMS_1(jsize) * SRCUXG_NITEMS_2(ksize)
#define SRCUXG(I, J, K) (srcuxg[(I-2) + SRCUXG_NITEMS_0(isize) * ((J-1) + (K-1) * SRCUXG_NITEMS_1(jsize))])

#endif // SRC_FLUID_ARRAYS_SRCUXG_H
