#if !defined(SRC_FLUID_ARRAYS_SRCUYB_H)
#define SRC_FLUID_ARRAYS_SRCUYB_H

/*
 * This file is generated by
 *   tools/define_arrays.py
 */

// [1:isize+0, 1:jsize+0, 1:ksize+0]
// number of additional cells w.r.t. 1, [i-k]size
#define SRCUYB_LNADD_0 0
#define SRCUYB_UNADD_0 0
#define SRCUYB_LNADD_1 0
#define SRCUYB_UNADD_1 0
#define SRCUYB_LNADD_2 0
#define SRCUYB_UNADD_2 0
// number of cells
#define SRCUYB_NITEMS_0(I) (I+0)
#define SRCUYB_NITEMS_1(J) (J+0)
#define SRCUYB_NITEMS_2(K) (K+0)
#define SRCUYB_NITEMS_ALL SRCUYB_NITEMS_0(isize) * SRCUYB_NITEMS_1(jsize) * SRCUYB_NITEMS_2(ksize)
#define SRCUYB(I, J, K) (srcuyb[(I-1) + SRCUYB_NITEMS_0(isize) * ((J-1) + (K-1) * SRCUYB_NITEMS_1(jsize))])

#endif // SRC_FLUID_ARRAYS_SRCUYB_H
