#if !defined(ARRAYS_DOMAIN_H)
#define ARRAYS_DOMAIN_H

/* This file is automatically generated by define_array.py */

/* xf */
#define XF_SIZE (isize+1)
#define XF(N) (xf[N-1])

/* xc */
#define XC_SIZE (isize+2)
#define XC(N) (xc[N])

/* dxf */
#define DXF_SIZE (isize+1)
#define DXF(N) (dxf[N-1])

/* dxc */
#define DXC_SIZE (isize+2)
#define DXC(N) (dxc[N])

/* lapuxx */
#define LAPUXX_SIZE (isize-1)
#define LAPUXX(N) (lapuxx[N-2])

/* lapuyx */
#define LAPUYX_SIZE (isize)
#define LAPUYX(N) (lapuyx[N-1])

/* lapuzx */
#define LAPUZX_SIZE (isize)
#define LAPUZX(N) (lapuzx[N-1])

/* lapuxy */
#define LAPUXY_SIZE (isize)
#define LAPUXY(N) (lapuxy[N-2])

/* lapuyy */
#define LAPUYY_SIZE (isize)
#define LAPUYY(N) (lapuyy[N-1])

/* lapuzy */
#define LAPUZY_SIZE (isize)
#define LAPUZY(N) (lapuzy[N-1])

/* lappx */
#define LAPPX_SIZE (isize)
#define LAPPX(N) (lappx[N-1])

/* lappy */
#define LAPPY_SIZE (isize)
#define LAPPY(N) (lappy[N-1])

#endif // ARRAYS_{name}_H
