#if !defined(ARRAYS_DOMAIN_H)
#define ARRAYS_DOMAIN_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

/* xf */
#define XF_SIZE (isize+1)
#define XF(N) (xf[N-1])

/* xc */
#define XC_SIZE (isize+2)
#define XC(N) (xc[N])

/* dxf */
#define DXF_SIZE (isize+1)
#define DXF(N) (dxf[N-1])

/* dxc */
#define DXC_SIZE (isize+2)
#define DXC(N) (dxc[N])

/* uxdifx */
#define UXDIFX_SIZE (isize-1)
#define UXDIFX(N) (uxdifx[N-2])

/* uydifx */
#define UYDIFX_SIZE (isize)
#define UYDIFX(N) (uydifx[N-1])

/* uzdifx */
#define UZDIFX_SIZE (isize)
#define UZDIFX(N) (uzdifx[N-1])

#endif // ARRAYS_{name}_H
